import type { NextPage } from 'next'
import Head from 'next/head'

// Components
import MainLayout from 'src/layouts'
// Models
import { PageWithMainLayout } from 'src/models/nextPage'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Test</div>
    </div>
  )
}

;(Home as PageWithMainLayout).layout = MainLayout

export default Home
